#include <stdexcept>
#include <string>
#include <GL/glew.h>
#include "renderer.h"

using std::runtime_error;
using std::string;

// Public methods.

Renderer::Renderer(int width, int height) {
    initGlew();
    resize(width, height);

    glEnable(GL_MULTISAMPLE);
    checkGlError();

    glGenVertexArrays(1, &vao_);
    checkGlError();
    glBindVertexArray(vao_);
    checkGlError();

    GLfloat vertices[] = {
       -1.0f, -1.0f, 0.0f,
       1.0f, -1.0f, 0.0f,
       0.0f,  1.0f, 0.0f,
    };

    glGenBuffers(1, &vbo_);
    checkGlError();
    glBindBuffer(GL_ARRAY_BUFFER, vbo_);
    checkGlError();
    glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);
    checkGlError();

    program_.loadVertexShader("src/shader.vert");
    program_.loadFragmentShader("src/shader.frag");
    program_.link();
    program_.use();

    glEnableVertexAttribArray(0);
    checkGlError();

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 0, nullptr);
    checkGlError();
}

void Renderer::render() const {
    glClearColor(0.2, 0, 0, 1.0);
    checkGlError();
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    checkGlError();

    glDrawArrays(GL_TRIANGLES, 0, 3);
    checkGlError();
}

void Renderer::resize(int width, int height) const {
    if (height == 0)
        height = 1;

    glViewport(0, 0, width, height);
    checkGlError();
}

// Private methods.

void Renderer::initGlew() const {
    glewExperimental = true;
    GLenum err = glewInit();
    // Ignore any OpenGL error generated by GLEW.
    glGetError();
    if (err != GLEW_OK) {
        string message = "GLEW: ";
        throw runtime_error(message + (const char*) glewGetErrorString(err));
    }
}
